name: Docker Image CI

on: pull_request_review
                 
jobs: 
  build: 
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u cloudnat --password-stdin
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag cloudnat/blue-hoc:latest
        - name: Push the latest Docker image
          run: docker push cloudnat/blue-hoc:latest
