name: Docker Image CI

on: 
  push:
  pull_request_review:
    branches:  [ master]
          
                 
jobs: 
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps: 
     - name: Checkout
       uses: actions/checkout@master
     - name: lint
       uses: github/super-linter@v4
       with:
          target: Dockerfile
       env:
         VALIDATE_ALL_CODEBASE: false
         DEFAULT_BRANCH: master
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  build: 
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u cloudnat --password-stdin
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag cloudnat/purple-hoc:latest
        - name: Push the latest Docker image
          run: docker push cloudnat/purple-hoc:latest
