name: Docker Image CI

on: pull_request_review
                 
jobs: 
  build: 
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u cloudnat --password-stdin
        - name: Get the version
          id: vars
          run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
        - name: Build the tagged Docker image
          run: docker build . --file Dockerfile --tag cloudnat/new-port:${{steps.vars.outputs.tag}}
        - name: Push the tagged Docker image
          run: docker push cloudnat/new-port:${{steps.vars.outputs.tag}}
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag cloudnat/new-port:latest
        - name: Push the latest Docker image
          run: docker push cloudnat/new-port:latest
