name: Docker Image CI

on: pull_request_review
                 
jobs: 
  build: 
     runs-on: ubuntu-latest
     steps:
        - uses: actions/checkout@v1
        - name: Login to DockerHub Registry
          run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u cloudnat --password-stdin
        - name: Build the latest Docker image
          run: docker build . --file Dockerfile --tag cloudnat/green-hoc:latest
        - name: Push the latest Docker image
          run: docker push cloudnat/green-hoc:latest
        - name: Post to a Slack channel
          id: slack
          uses: slackapi/slack-github-action@v1.17.0
          with:
            # Slack channel id, channel name, or user id to post message.
            # See also: https://api.slack.com/methods/chat.postMessage#channels
            channel-id: 'C02V0U9NF6J'
            # For posting a simple plain text message
            slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
          env:
            SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
