name: Lint Code Base

on: push

jobs: 
  lint:
    runs-on: ubuntu-latest
    steps: 
     - name: Checkout
       uses: actions/checkout@master
     - name: lint
       uses: github/super-linter@v4
       with:
          target: Dockerfile
       env:
         VALIDATE_ALL_CODEBASE: false
         DEFAULT_BRANCH: master
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}